spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ops
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: "classpath:application-secret.yml"

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  mail:
    host: smtp.example.com
    port: 587
    username: ops-username
    password: ops-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cors:
  allow:
    origins: https://test.url
    methods: GET, POST, PUT, DELETE, PATCH, OPTIONS

